/// Flutter icons Linecons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Linecons
///      fonts:
///       - asset: fonts/Linecons.ttf
///
///
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
///
import 'package:flutter/widgets.dart';

class Linecons {
  Linecons._();

  static const _kFontFam = 'Linecons';

  static const IconData music_1 = IconData(0xe825, fontFamily: _kFontFam);
  static const IconData search_1 = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData mail = IconData(0xe827, fontFamily: _kFontFam);
  static const IconData heart_1 = IconData(0xe828, fontFamily: _kFontFam);
  static const IconData star_1 = IconData(0xe829, fontFamily: _kFontFam);
  static const IconData user_1 = IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData videocam = IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData camera_1 = IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData photo = IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData attach = IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData lock_1 = IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData eye_1 = IconData(0xe830, fontFamily: _kFontFam);
  static const IconData tag_1 = IconData(0xe831, fontFamily: _kFontFam);
  static const IconData thumbs_up = IconData(0xe832, fontFamily: _kFontFam);
  static const IconData pencil = IconData(0xe833, fontFamily: _kFontFam);
  static const IconData comment_1 = IconData(0xe834, fontFamily: _kFontFam);
  static const IconData location = IconData(0xe835, fontFamily: _kFontFam);
  static const IconData cup = IconData(0xe836, fontFamily: _kFontFam);
  static const IconData trash_1 = IconData(0xe837, fontFamily: _kFontFam);
  static const IconData doc = IconData(0xe838, fontFamily: _kFontFam);
  static const IconData note = IconData(0xe839, fontFamily: _kFontFam);
  static const IconData cog_1 = IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData params = IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData calendar_1 = IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData sound = IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData clock_1 = IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData lightbulb_1 = IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData tv_1 = IconData(0xe840, fontFamily: _kFontFam);
  static const IconData desktop_1 = IconData(0xe841, fontFamily: _kFontFam);
  static const IconData mobile_1 = IconData(0xe842, fontFamily: _kFontFam);
  static const IconData cd = IconData(0xe843, fontFamily: _kFontFam);
  static const IconData inbox_1 = IconData(0xe844, fontFamily: _kFontFam);
  static const IconData globe_1 = IconData(0xe845, fontFamily: _kFontFam);
  static const IconData cloud_1 = IconData(0xe846, fontFamily: _kFontFam);
  static const IconData paper_plane = IconData(0xe847, fontFamily: _kFontFam);
  static const IconData fire_1 = IconData(0xe848, fontFamily: _kFontFam);
  static const IconData graduation_cap =
      IconData(0xe849, fontFamily: _kFontFam);
  static const IconData megaphone = IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData database_1 = IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData key_1 = IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData beaker = IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData truck_1 = IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData money = IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData food = IconData(0xe850, fontFamily: _kFontFam);
  static const IconData shop = IconData(0xe851, fontFamily: _kFontFam);
  static const IconData diamond = IconData(0xe852, fontFamily: _kFontFam);
  static const IconData t_shirt = IconData(0xe853, fontFamily: _kFontFam);
  static const IconData wallet_1 = IconData(0xe854, fontFamily: _kFontFam);
}
